version: 1.0.{build}
before_build:
  - appveyor DownloadFile https://raw.githubusercontent.com/appveyor/ci/master/scripts/nuget-restore.cmd
  - nuget-restore source/NDomain.sln
build:
  verbosity: minimal
  project: source\NDomain.sln
before_test:
 - nuget install redis-64 -excludeversion
 - redis-64\tools\redis-server.exe --service-install
 - redis-64\tools\redis-server.exe --service-start
services:
 - mssql2014
test:
  # all except assemblies to test
  assemblies:
    except:
      - '**\NDomain.Tests.Common.dll'